server:
  port: '8086'
  servlet:
    context-path: /api/flights

spring:
  application:
    name: flight-booking-service
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/flight-booking
    username: ${USERNAME:db_user}
    password: ${PASSWORD:123qwe}
  threads:
    virtual:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
app:
  kafka:
    topic-name: flight.email.topic
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces


