version: '3.9'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/data:/data/db
