server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: flight-search-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/flights/search/**
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AddResponseHeader=My-Header-Good,Good
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
    default-filters:
      - name: Retry
        args:
          retry: 5
          methods: GET
          backoff:
            firstBackOff: 10ms
            maxBackOff: 50ms
            factor: 2
            basedOnPreviousValue: false



  application:
    name: edge-service
  data.redis.host: localhost
  data.redis.port: 6379


opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
    probabilistic-sampler:
      sampling-rate: 0.5

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics


logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG